#!/usr/bin/env bash
#process and pid file
handle_sigterm_quit() {
  echo "I hate the kill command"
  rm -f /var/run/myscript.pid
  exit 1
}

handle_sigint() {
  echo "Y U no love me?!"
}

trap 'handle_sigterm_quit' SIGTERM SIGQUIT

trap 'handle_sigint' SIGINT

echo $$ > /var/run/myscript.pid

while true; do
  echo "To infinity and beyond"
  sleep 1
done
